// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzmkuDGtHMMFJEw91Lx3nlyDIfkuNkngg',
    appId: '1:492204333489:web:1d20f8eabdf038ce728590',
    messagingSenderId: '492204333489',
    projectId: 'talk-talk-8f30f',
    authDomain: 'talk-talk-8f30f.firebaseapp.com',
    storageBucket: 'talk-talk-8f30f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxGjqoUNG4Yj5oC1HkaflS5uY-qHH5mm4',
    appId: '1:492204333489:android:d8993595fcdc8584728590',
    messagingSenderId: '492204333489',
    projectId: 'talk-talk-8f30f',
    storageBucket: 'talk-talk-8f30f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUqzJ-fy6FVip1sn7D-WBEASR_7gGgaqo',
    appId: '1:492204333489:ios:2ab269a07d2b5270728590',
    messagingSenderId: '492204333489',
    projectId: 'talk-talk-8f30f',
    storageBucket: 'talk-talk-8f30f.appspot.com',
    iosBundleId: 'com.example.talkTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUqzJ-fy6FVip1sn7D-WBEASR_7gGgaqo',
    appId: '1:492204333489:ios:2ab269a07d2b5270728590',
    messagingSenderId: '492204333489',
    projectId: 'talk-talk-8f30f',
    storageBucket: 'talk-talk-8f30f.appspot.com',
    iosBundleId: 'com.example.talkTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzmkuDGtHMMFJEw91Lx3nlyDIfkuNkngg',
    appId: '1:492204333489:web:bd0941f2ee9b27c2728590',
    messagingSenderId: '492204333489',
    projectId: 'talk-talk-8f30f',
    authDomain: 'talk-talk-8f30f.firebaseapp.com',
    storageBucket: 'talk-talk-8f30f.appspot.com',
  );

}